##################
# Hack the Crous #
##################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hackthecrous
  namespace: services
spec:
  project: default
  source:
    repoURL: "https://github.com/Courtcircuits/polytech-cluster"
    path: projects/hackthecrous
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: triggerrally
  namespace: services
spec:
  project: default
  source:
    repoURL: "https://github.com/Courtcircuits/polytech-cluster"
    path: projects/triggerrally
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxmox
  namespace: services
spec:
  project: default
  source:
    repoURL: "https://github.com/Courtcircuits/polytech-cluster"
    path: projects/proxmox-doc
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---

